api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: "bitrix"

log:
  level: DEBUG

http:
  routers:
    dashboard:
      rule: "Host(`dashboard.localhost`)"
      service: "api@internal"
      entryPoints:
        - "web"
