variables:
  CI_REGISTRY_IMAGE: "1cbit-tyk-gateway"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

build-image:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/tyk-gateway/$CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY/tyk-gateway/$CI_REGISTRY_IMAGE
